# Generated by Django 4.2 on 2024-06-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveBigIntegerField(verbose_name='商品コード')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price', models.PositiveBigIntegerField(verbose_name='単価')),
                ('stock', models.PositiveBigIntegerField(verbose_name='在庫数')),
                ('purchase_code', models.CharField(choices=[('', '選択してください'), ('1', 'T1111'), ('2', 'T08754395'), ('3', 'T768594444')], max_length=100, verbose_name='仕入れ先コード')),
            ],
        ),
    ]
